server:
  port: 0

spring:
  application:
    name: assignment-service
  cloud:
    discovery:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${ASSIGNMENT_DB_URL:jdbc:postgresql://localhost:5435/assignmentdb}
    username: ${ASSIGNMENT_DB_USER:postgres}
    password: ${ASSIGNMENT_DB_PASS:postgres}
    hikari:
      maximum-pool-size: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      user-service:
        baseConfig: default
      product-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      user-service:
        baseConfig: default
      product-service:
        baseConfig: default

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

logging:
  level:
    com.example: DEBUG
    org.springframework.cloud: INFO