server:
  port: 0

spring:
  application:
    name: product-service
  cloud:
    discovery:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5434/productdb}
    username: ${PRODUCT_DB_USER:postgres}
    password: ${PRODUCT_DB_PASS:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        record-exceptions:
          - feign.RetryableException
          - java.net.ConnectException
          - java.net.UnknownHostException
          - java.io.IOException
    instances:
      user-service:
        baseConfig: default
      application-service:
        baseConfig: default
      assignment-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      user-service:
        baseConfig: default
      application-service:
        baseConfig: default
      assignment-service:
        baseConfig: default

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

logging:
  level:
    com.example: DEBUG
    org.springframework.cloud: INFO