server:
  port: 0

spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
    r2dbc:
      url: ${USER_DB_URL:r2dbc:postgresql://localhost:5433/userdb}
      username: ${USER_DB_USER:postgres}
      password: ${USER_DB_PASS:postgres}
      pool:
        enabled: true
        max-size: 10
    flyway:
      enabled: true
      url: ${USER_DB_JDBC_URL:jdbc:postgresql://localhost:5433/userdb}
      user: ${USER_DB_USER:postgres}
      password: ${USER_DB_PASS:postgres}
      locations: classpath:db/migration

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

  resilience4j:
    circuitbreaker:
      configs:
        default:
          registerHealthIndicator: true
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 20
          minimumNumberOfCalls: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 30s
          permittedNumberOfCallsInHalfOpenState: 3
      instances:
        application-service:
          baseConfig: default
    timelimiter:
      configs:
        default:
          timeoutDuration: 2s
      instances:
        application-service:
          baseConfig: default

  feign:
    client:
      config:
        default:
          connect-timeout: 5000
          read-timeout: 5000
          logger-level: basic

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: false

  logging:
    level:
      com.example: DEBUG
      org.springframework.cloud: INFO